import { pgTable, uuid, text, timestamp, boolean } from "drizzle-orm/pg-core";

export const leads = pgTable("leads", {
  id: uuid("id").primaryKey().defaultRandom(),
  firstName: text("first_name").notNull(),
  lastName: text("last_name").notNull(),
  email: text("email").notNull(),
  phone: text("phone").notNull(),
  serviceNeeded: text("service_needed"),
  message: text("message"),
  preferredContact: text("preferred_contact"),
  source: text("source").default("website"),
  status: text("status").default("new"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
});

export const inquiries = pgTable("inquiries", {
  id: uuid("id").primaryKey().defaultRandom(),
  firstName: text("first_name").notNull(),
  lastName: text("last_name").notNull(),
  email: text("email").notNull(),
  phone: text("phone").notNull(),
  serviceNeeded: text("service_needed").notNull(),
  message: text("message"),
  status: text("status").default("new"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
});

export const referrals = pgTable("referrals", {
  id: uuid("id").primaryKey().defaultRandom(),
  referrerName: text("referrer_name").notNull(),
  referrerPhone: text("referrer_phone").notNull(),
  referrerEmail: text("referrer_email").notNull(),
  patientName: text("patient_name").notNull(),
  patientPhone: text("patient_phone").notNull(),
  serviceNeeded: text("service_needed").notNull(),
  notes: text("notes"),
  status: text("status").default("new"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
});

export const applications = pgTable("applications", {
  id: uuid("id").primaryKey().defaultRandom(),
  firstName: text("first_name").notNull(),
  lastName: text("last_name").notNull(),
  email: text("email").notNull(),
  phone: text("phone").notNull(),
  address: text("address"),
  city: text("city"),
  state: text("state"),
  zip: text("zip"),
  position: text("position").notNull(),
  desiredPayRate: text("desired_pay_rate"),
  availableStartDate: text("available_start_date"),
  schedulePreference: text("schedule_preference"),
  authorizedToWork: text("authorized_to_work"),
  felonyConviction: text("felony_conviction"),
  felonyExplanation: text("felony_explanation"),
  highestEducation: text("highest_education"),
  schoolName: text("school_name"),
  certifications: text("certifications"),
  cprExpiration: text("cpr_expiration"),
  driversLicense: text("drivers_license"),
  hasReliableTransport: text("has_reliable_transport"),
  employer1Name: text("employer1_name"),
  employer1Title: text("employer1_title"),
  employer1Dates: text("employer1_dates"),
  employer1Duties: text("employer1_duties"),
  employer1ReasonForLeaving: text("employer1_reason_for_leaving"),
  employer2Name: text("employer2_name"),
  employer2Title: text("employer2_title"),
  employer2Dates: text("employer2_dates"),
  employer2Duties: text("employer2_duties"),
  employer2ReasonForLeaving: text("employer2_reason_for_leaving"),
  reference1Name: text("reference1_name"),
  reference1Phone: text("reference1_phone"),
  reference1Relationship: text("reference1_relationship"),
  reference2Name: text("reference2_name"),
  reference2Phone: text("reference2_phone"),
  reference2Relationship: text("reference2_relationship"),
  resumeNotes: text("resume_notes"),
  additionalInfo: text("additional_info"),
  agreesToTerms: boolean("agrees_to_terms").default(false),
  message: text("message"),
  status: text("status").default("new"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
});

export const adminUsers = pgTable("admin_users", {
  id: uuid("id").primaryKey().defaultRandom(),
  email: text("email").notNull().unique(),
  passwordHash: text("password_hash").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
});
